likes(syed,sing).
boy(nazim).
eats(syed,icecream).
owns(natraj,guitar).
brothers(nazim,nasim).
cat(tom).
loves_to_eat(shehnaz,maggie).
of_color(hair,black).
loves_to_play_games(mudit).
lazy(rishabh).
happy(samiran).